version: "3.9"

services:
  portfolio:
    build: .
    container_name: portfolio_app
    ports:
      - "3000:80"
      - "3001:443"
    volumes:
      - ./nginx/cert.pem:/etc/nginx/cert.pem:ro
      - ./nginx/key.pem:/etc/nginx/key.pem:ro
    restart: unless-stopped